# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Noelle's Blog"
email:
description: >- # this means to ignore newlines until "baseurl:"
  My name is Noelle. I've been a hyperfixated nerd for way too long
  This is my pawnsho-- my blog and I'll write about things I think
  are either fun or important. Thanks for reading.
twitter_username: AuroraNemoia
github_username: AuroraNemoia
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "neon"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Toronto

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Noelle Nemoia"
  avatar : "/assets/images/Aurora.png"
  bio    : "I'm definitely human, I swear."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://nemoia.ai"
    - label: "K2VR"
      icon: "fas fa-fw fa-link"
      url: "https://k2vr.tech"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://wetdry.world/@AuroraNemoia"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AuroraNemoia"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AuroraNemoia"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"

footer:
  links:
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://wetdry.world/@AuroraNemoia"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AuroraNemoia"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
